# Generated by Django 4.2.10 on 2024-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=20)),
                ('roomtype', models.CharField(default='Single', max_length=15)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
